### PR TITLE
Logo and popup

### PR DESCRIPTION
**Pull request by thota007**

### CODE REVIEW

**Comment by sspathare97** [comment]
Please use moment.js to format the datetime as '21 March at 11:01 PM'

**Comment by sspathare97** [comment]
Also move location to the left and timestamp to the right if possible

**Comment by sspathare97** [comment]
Also, show section and subsection info- ignore subsection when null

**Review by sspathare97 — CHANGES_REQUESTED** [review]
Remove subcategory

**Comment by thota007** [comment]
removed sub category and readied subsection to article card

**Pull request merged**
